SELECT EMP_ID, EMP_NAME, EMP_PASSWORD, BIRTH_DATE, GENDER, MARITAL_STATUS, JPNLEVEL_NAME, DEPT_NAME, JOIN_DATE, POSITION_NAME, EMAIL, PHONE 

FROM EMPLOYEE AS Emp

INNER JOIN JAPANESE_LEVEL AS Jap ON Emp.JPNLEVEL_ID = Jap.JPNLEVEL_ID 

INNER JOIN DEPARTMENT AS Dep ON Emp.DEPT_ID = Dep.DEPT_ID

INNER JOIN POSITION AS Pos ON Emp.POSITION_ID = Pos.POSITION_ID;
